// Tous les textes de l'interface, en français et en anglais.
export const TRADS = {
  fr: {
    langueBouton: '🇫🇷 Français',
    connexion: 'Connexion',
    accueilTitre: 'Loremasters',
    boutonImporter: 'Importer un deck',
    boutonMesDecks: 'Mes decks',
    vosDecks: 'Vos Decks',
    importAutre: 'Importer un autre deck',
    contient: 'Contient',
    cartes: 'cartes',
    encres: 'Encres',
    plansJeu: 'Faire mes plans de jeu',
    modifierListe: 'Modifier la Liste',
    supprimer: 'Supprimer',
    ajouterCarte: 'Ajouter une carte',
    retourDecks: 'Retour à mes decks',
    biblioTactique: 'Bibliothèque Tactique',
    hubDesc: 'Sélectionnez une stratégie existante pour la consulter/modifier, ou lancez-en une nouvelle.',
    modifierPlan: 'Modifier Plan',
    archetype: 'Archétype',
    creerNouvelleStrat: 'Créer une nouvelle stratégie',
    retourIndex: 'Retourner à la liste des plans de jeu',
    configTactique: 'Configuration Tactique',
    feuilleMatch: 'Feuille de Match',
    choixPositionTour: 'Avant le séquenceur, choisis ta position :',
    joueurCommence: 'On commence',
    joueurSecond: 'On est second',
    choixBicolo: '1. Choix de la bicolorité adverse',
    choixArchetype: "2. Quel type d'archétype est-ce ?",
    placeholderArchetype: 'Ex: Aggro, Contrôle, Midrange, Steelsong...',
    matchupActuel: 'Matchup Actuel',
    mulliganOptimal: 'Mulligan Optimal',
    lignesPlay: 'Lignes de Play',
    placeholderLignes: 'Écris tes lignes de jeu détaillées ici...',
    enregistrerFermer: 'Fermer ce plan',
    sauvegardeAuto: 'Sauvegarde automatique activée',
    sauvegardeA: 'Sauvegardé à',
    exporterImage: 'Télécharger en image',
    exportEnCours: 'Génération de l\'image...',
    exportErreur: 'Impossible de générer l\'image, réessaie.',
    deconnexion: 'Déconnexion',
    profilTitre: 'Profil & données personnelles',
    pseudoLabel: 'Pseudo affiché',
    pseudoAide: 'Ce nom remplace ton pseudo Discord dans l\'application.',
    enregistrerProfil: 'Enregistrer',
    pseudoEnregistre: 'Pseudo enregistré !',
    rgpdTitre: 'Tes données (RGPD)',
    rgpdTexte: 'Loremasters stocke uniquement : ton identifiant Discord (pseudo, avatar, e-mail fournis par Discord), tes decks et tes plans de jeu. Ces données servent seulement à faire fonctionner l\'application, ne sont jamais partagées ni utilisées à d\'autres fins, et tu peux les exporter ou les supprimer à tout moment ci-dessous.',
    exporterDonnees: 'Exporter mes données (JSON)',
    supprimerCompte: 'Supprimer mon compte et toutes mes données',
    supprimerConfirme1: 'Supprimer définitivement ton compte et toutes tes données (decks, plans de jeu) ? Cette action est irréversible.',
    supprimerConfirme2: 'Dernière confirmation : tout sera effacé, y compris sur ce navigateur. Continuer ?',
    suppressionErreur: 'La suppression a échoué, réessaie ou contacte l\'administrateur.',
    nouvelleCarte: 'Nouvelle Carte',
    gestionRatio: 'Gestionnaire de Ratio Visuel',
    modifDesc: 'Modifie ou intègre proprement tes cartes sans casser ta base de données',
    cibleEdition: "Cible d'édition",
    selectionDroite: 'Sélection à droite',
    visuelApi: "Utilise la recherche de droite pour sélectionner le visuel officiel...",
    quantiteDesiree: 'Quantité désirée',
    enregistrerRatio: 'Enregistrer Ratio',
    retirer: 'Retirer',
    consigneRecherche: 'Chercher une carte dans la base globale',
    placeholderRecherche: "Tapez le nom d'un personnage, d'une action...",
    apiConnexion: "Connexion à l'API Lorcana en cours...",
    injecter: 'Injecter',
    remplacer: 'Remplacer',
    rechercheConsigneVide: 'Entrez au moins 2 lettres pour lancer la recherche globale...',
    aucunResultat: 'Aucune carte trouvée pour cette recherche.',
    boutonAjouterDeck: 'Sauvegarder ce deck',
    nomDeckLabel: 'Nom de votre Deck',
    listeTexteLabel: 'Liste au format texte',
    erreurImport: "Aucune carte valide n'a été trouvée.",
    nouveauDeckTitre: 'Ajouter un nouveau deck',
    fermer: 'Fermer',
    emplacement: 'Sélectionner pour l\'emplacement',
    viderEmplacement: 'Vider cet emplacement',
    manaCurve: 'Courbe d\'Encre',
    reglesTitre: 'Validité du Deck',
    regleCartes: '60+ cartes',
    regleEncres: 'Max 2 couleurs',
    regleMaxExemplaires: 'Pas d\'excès (>4)'
  },
  en: {
    langueBouton: '🇬🇧 English',
    connexion: 'Login',
    accueilTitre: 'Loremasters',
    boutonImporter: 'Import a deck',
    boutonMesDecks: 'My decks',
    vosDecks: 'My Decks',
    importAutre: 'Import another deck',
    contient: 'Contains',
    cartes: 'cards',
    encres: 'Inks',
    plansJeu: 'Game Plans',
    modifierListe: 'Edit Decklist',
    supprimer: 'Delete',
    ajouterCarte: 'Add a card',
    retourDecks: 'Back to my decks',
    biblioTactique: 'Tactical Library',
    hubDesc: 'Select an existing strategy to view/edit, or start a new one.',
    modifierPlan: 'Edit Plan',
    archetype: 'Archetype',
    creerNouvelleStrat: 'Create a new strategy',
    retourIndex: 'Back to strategy list',
    configTactique: 'Tactical Setup',
    feuilleMatch: 'Match Sheet',
    choixPositionTour: 'Before the sequencer, choose your position:',
    joueurCommence: 'We start',
    joueurSecond: 'We are second',
    choixBicolo: "1. Choose opponent's inks",
    choixArchetype: '2. What kind of archetype is it?',
    placeholderArchetype: 'Ex: Aggro, Control, Midrange, Steelsong...',
    matchupActuel: 'Current Matchup',
    mulliganOptimal: 'Optimal Mulligan',
    lignesPlay: 'Lines of Play',
    placeholderLignes: 'Write your detailed lines of play here...',
    enregistrerFermer: 'Close this plan',
    sauvegardeAuto: 'Auto-save enabled',
    sauvegardeA: 'Saved at',
    exporterImage: 'Download as image',
    exportEnCours: 'Generating image...',
    exportErreur: 'Could not generate the image, please retry.',
    deconnexion: 'Log out',
    profilTitre: 'Profile & personal data',
    pseudoLabel: 'Display name',
    pseudoAide: 'This name replaces your Discord username in the app.',
    enregistrerProfil: 'Save',
    pseudoEnregistre: 'Name saved!',
    rgpdTitre: 'Your data (GDPR)',
    rgpdTexte: 'Loremasters only stores: your Discord identity (username, avatar, e-mail provided by Discord), your decks and your game plans. This data is used solely to run the app, is never shared or used for anything else, and you can export or delete it at any time below.',
    exporterDonnees: 'Export my data (JSON)',
    supprimerCompte: 'Delete my account and all my data',
    supprimerConfirme1: 'Permanently delete your account and all your data (decks, game plans)? This cannot be undone.',
    supprimerConfirme2: 'Last confirmation: everything will be erased, including on this browser. Continue?',
    suppressionErreur: 'Deletion failed, please retry or contact the administrator.',
    nouvelleCarte: 'New Card',
    gestionRatio: 'Visual Ratio Manager',
    modifDesc: 'Modify or integrate your cards safely without breaking your database',
    cibleEdition: 'Target Edit',
    selectionDroite: 'Select on the right',
    visuelApi: 'Use the search bar on the right to select the official artwork...',
    quantiteDesiree: 'Desired Quantity',
    enregistrerRatio: 'Save Ratio',
    retirer: 'Remove',
    consigneRecherche: 'Search a card in the global database',
    placeholderRecherche: 'Type a character name, an action...',
    apiConnexion: 'Connecting to Lorcana API...',
    injecter: 'Add to Deck',
    remplacer: 'Replace',
    rechercheConsigneVide: 'Enter at least 2 letters to launch global search...',
    aucunResultat: 'No cards found for this search.',
    boutonAjouterDeck: 'Save this deck',
    nomDeckLabel: 'Deck Name',
    listeTexteLabel: 'Text Decklist',
    erreurImport: 'No valid cards were found.',
    nouveauDeckTitre: 'Add a new deck',
    fermer: 'Close',
    emplacement: 'Select for slot',
    viderEmplacement: 'Clear this slot',
    manaCurve: 'Ink Curve',
    reglesTitre: 'Deck Validity',
    regleCartes: '60+ cards',
    regleEncres: 'Max 2 inks',
    regleMaxExemplaires: 'No excess (>4)'
  }
}
